/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Froilan' at '15/11/14 11:06 PM' with Gradle 2.2
 *
 * @author Froilan, @date 15/11/14 11:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
